### ISSUE TITLE
Text rendering is dramatically slower than equivalent billboard sprites

### ISSUE THREAD

**Issue by alice-i-cecile** [kulkalkul/bevy_mod_billboard#8]
When experimenting with this crate for information visualization, I found that recomputing text was incredibly slow. Actually rendering it was fine, but changing it crashed my performance from 100 FPS to 10 FPS.

Swapping to icons (using this crate as well) in https://github.com/Leafwing-Studios/Emergence/pull/756 resolved the performance problems completely.

A reader had a suggestion for better optimization:

> [Is the gold standard not still to render the font to an atlas texture and draw with that?] ( https://elk.zone/tech.lgbt/@itsybitesyspider@peoplemaking.games/110259520099233824)

**Comment by kulkalkul** [comment]
Bevy (and bevy_mod_billboard) already uses font atlasses to render the text. So I assume the issue is different here. Only thing bevy_mod_billboard does differently is ability to have multiple font atlasses, so ~~they can be coloured differently~~ different fonts can be used. I suppose that logic can be combined into single font atlas with some mesh attributes, but I'm not sure if this is the hot path that's responsible for this performance hit. I recall some possible optimization for text rendering that I thought I could do it later, was related to changing text quickly.

May I ask for a reproducable demo if you have the time and will to implement one? I can investigate and hopefully figure a solution in several days (could be tomorrow, or 3-4 days later). 😅

I love how you find all this stuff that's wrong with the crate. It is great to see someone is actually using something you did and return with valuable feedback! 💯

**Comment by kulkalkul** [comment]
Thoughts on the topic;

Each character is a quad and all text is combined into same mesh. So, rendering performance-wise, single quad icons will always outperform text. I think only having this overhead is the best scenario for the performance if other issues can be solved. So this should be the long-term goal.

Instead of using already existing font atlas images, it creates an array texture and combines them into single texture. This involves texture copying, which is why text recomputing is slower than icon. This allows multiple fonts to be used together. But right now, it also copies single font atlas to make the data uniform (so all of them become array textures). There are 3 possible approaches to improve it:
- Memoizing font atlas so it only recomputes when font changes.
- Using font atlas only for multiple font texts.
- Finding an alternative for copying images into texture array, directly using texture atlasses.

If I'm not wrong, currently, even though fonts used are same, it loads copies of font atlasses into GPU memoy for each rendered text. This increases memory footprint unnecessarily A LOT (I was getting 2gbs of gpu memory usage with stress_test demo reduced to 5 radius). I only know some basics about rendering, so not sure if this is the proper way to solve it, but I suppose this can be solved with combining similar fonts into same mesh and batch rendering them at once? So they all use the same texture, with no unnecessary copies. I know bevy's 2d workflow does batching for sprites, so it is possible I guess?

Again, related to batching, right now both texts and textures are sent individually to the GPU. Batching should also improve performance in that regard.

One issue with batching though, is, doing it for 3D makes culling harder iirc. So, I have no idea on solving that.

**Comment by kulkalkul** [comment]
Had lots of time thinking about this while trying Godot out. I think using texture atlas is wrong approach here. Not that it can't be done, but doing it without that feels easier. Bathcing them by their fonts instead feels like solves all the issues above. I'll try that approach and see how well it performs, soonish.
